/// for messages

//{
// title: "Destination Wedding Planning",
// status: "In Progress",
// startDate: "June 10, 2026",
// endDate: "November 20, 2026",
// company: "EverAfter Weddings Nepal",
// description:
//   "Complete wedding planning project covering venue coordination, vendor management, guest logistics, and day-of execution.",
// budget: {
//   total: "$9,000",
//   paid: "$2,700",
//   pending: "$6,300",
//   schedule: [
//     {
//       milestone: "Planning Kickoff",
//       amount: "$2,700 (30%)",
//       status: "Paid",
//       date: "June 10, 2026",
//     },
//     {
//       milestone: "Vendor Finalization",
//       amount: "$2,700 (30%)",
//       status: "Pending",
//       date: "August 15, 2026",
//     },
//     {
//       milestone: "Event Completion",
//       amount: "$3,600 (40%)",
//       status: "Pending",
//       date: "November 20, 2026",
//     },
//   ],
// },
// timeline: [
//   {
//     phase: "Consultation & Planning",
//     startDate: "June 10, 2026",
//     endDate: "June 30, 2026",
//     status: "Completed",
//     description:
//       "Initial consultations, style preference mapping, and budget planning.",
//   },
//   {
//     phase: "Venue & Vendor Booking",
//     startDate: "July 1, 2026",
//     endDate: "August 20, 2026",
//     status: "In Progress",
//     description:
//       "Finalize venue, photographer, caterer, decorator, makeup, and entertainment.",
//   },
//   {
//     phase: "Design & Logistics",
//     startDate: "August 21, 2026",
//     endDate: "October 31, 2026",
//     status: "Not Started",
//     description:
//       "Invitation design, seating layout, transportation plans, and guest coordination.",
//   },
//   {
//     phase: "Final Preparation",
//     startDate: "November 1, 2026",
//     endDate: "November 18, 2026",
//     status: "Not Started",
//     description:
//       "Vendor confirmations, rehearsal planning, and final checklist review.",
//   },
//   {
//     phase: "Wedding Day Execution",
//     startDate: "November 19, 2026",
//     endDate: "November 20, 2026",
//     status: "Not Started",
//     description: "On-site event management and complete wedding day coordination.",
//   },
// ],
// client: {
//   name: "Aarav & Sita",
//   position: "Bride & Groom",
//   email: "aarav.sita@email.com",
//   phone: "+977 9800000000",
// },
// requirements: [
//   "Traditional ceremony with modern stage setup",
//   "Indoor venue with backup weather plan",
//   "Photography and cinematic videography coverage",
//   "Vegetarian and non-vegetarian catering options",
//   "Guest transportation for out-of-town attendees",
//   "End-to-end day-of coordination support",
// ],
// deliverables: [
//   "Wedding planning timeline and checklist",
//   "Confirmed vendor list with contact details",
//   "Decor and stage concept board",
//   "Guest logistics and seating plan",
//   "Full wedding day coordination",
//   "Post-event vendor settlement summary",
// ],
// nextSteps: [
//   "Finalize venue booking and deposit",
//   "Confirm photographer and makeup artist",
//   "Approve invitation design draft",
//   "Schedule family coordination meeting",
// ],
// files: [
//   { name: "Wedding Brief.pdf", size: "2.1 MB", date: "June 8, 2026" },
//   { name: "Venue Options.pdf", size: "4.3 MB", date: "June 9, 2026" },
//   { name: "Guest List Draft.xlsx", size: "1.2 MB", date: "June 9, 2026" },
// ],
//}

const users = [
  {
    name: "Aarav & Sita",
    message: "Can you share your Mehendi package for Kathmandu?",
    image: "/images/placeholder-614.webp",
    time: "9:00 AM",
    id: 1,
  },
  {
    name: "Himalaya Catering",
    message: "Tasting slots available this Saturday.",
    image: "/images/placeholder-614.webp",
    time: "9:20 AM",
    id: 2,
  },
  {
    name: "EverAfter Photography",
    message: "We sent your pre-wedding moodboard.",
    image: "/images/placeholder-614.webp",
    time: "10:10 AM",
    id: 3,
  },
  {
    name: "Lotus Banquet",
    message: "Hall is available for Nov 21 in Lalitpur.",
    image: "/images/placeholder-614.webp",
    time: "10:45 AM",
    id: 4,
  },
  {
    name: "DJ Neon",
    message: "Please share your Sangeet playlist preferences.",
    image: "/images/placeholder-614.webp",
    time: "11:30 AM",
    id: 5,
  },
  {
    name: "Floral Studio Nepal",
    message: "Theme mockups are ready in your dashboard.",
    image: "/images/placeholder-614.webp",
    time: "12:15 PM",
    id: 6,
  },
  {
    name: "Priya Makeup Artist",
    message: "Bridal trial available on Friday afternoon.",
    image: "/images/placeholder-614.webp",
    time: "1:05 PM",
    id: 7,
  },
  {
    name: "Golden Lens Films",
    message: "Drone coverage add-on quote sent.",
    image: "/images/placeholder-614.webp",
    time: "2:00 PM",
    id: 8,
  },
];

/// ongoing jobs data
const ongoingProjects = [
  {
    projectName: "Kathmandu Wedding Photography",
    category: "Photography & Videography",
    description: "Two-day coverage for engagement and wedding highlights.",
    budget: "$1,200",
    deadline: "November 20, 2026",
    clientName: "Aarav & Sita",
  },
  {
    projectName: "Lalitpur Banquet Decoration",
    category: "Decoration & Floral Design",
    description: "Mandap setup, stage floral wall, and aisle styling.",
    budget: "$950",
    deadline: "October 12, 2026",
    clientName: "Riya Events",
  },
  {
    projectName: "Bhaktapur Bridal Makeup",
    category: "Makeup & Beauty",
    description:
      "Bridal plus 4 family members with full-day touch-up support.",
    budget: "$450",
    deadline: "September 6, 2026",
    clientName: "Mina Shrestha",
  },
  {
    projectName: "Pokhara Destination Coordination",
    category: "Wedding Planning & Coordination",
    description: "Timeline, vendor coordination, and guest logistics.",
    budget: "$2,300",
    deadline: "December 5, 2026",
    clientName: "Karma & Nima",
  },
  {
    projectName: "Chitwan Live Catering Service",
    category: "Catering & Bakery",
    description: "Buffet setup for 350 guests with live stations.",
    budget: "$2,000",
    deadline: "November 2, 2026",
    clientName: "Bista Family",
  },
  {
    projectName: "Butwal Wedding Entertainment Setup",
    category: "Music & Entertainment",
    description:
      "DJ, sound system, and host for Sangeet and reception.",
    budget: "$780",
    deadline: "October 1, 2026",
    clientName: "K.C. Wedding House",
  },
];

const languageTags = [
  "English",
  "Nepali",
  "Hindi",
  "Nepal Bhasa",
  "Maithili",
  "Bhojpuri",
  "Tamang",
  "Gurung",
  "Urdu",
];

const countries = [
  { name: "Afghanistan", code: "AF" },
  { name: "Åland Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic People'S Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

const jobCategories = [
  "Wedding Planning & Coordination",
  "Photography & Videography",
  "Makeup & Beauty",
  "Decoration & Floral Design",
  "Catering & Bakery",
  "Venue Management",
  "Music & Entertainment",
  "Bridal Wear & Tailoring",
  "Invitation & Stationery Design",
  "Transportation & Logistics",
  "Mehendi & Ritual Services",
  "Event Hosting & Anchoring",
  "Lighting & Sound Setup",
  "Gift & Favors Curation",
  "Honeymoon Travel Planning",
];

const skills = [
  "Bridal Photography",
  "Cinematic Videography",
  "Photo Editing",
  "Bridal Makeup",
  "Hair Styling",
  "Floral Arrangement",
  "Mandap Decoration",
  "Stage Decoration",
  "Live Catering",
  "Cake Design",
  "DJ Performance",
  "Sound Mixing",
  "Event Anchoring",
  "Invitation Design",
  "Transportation Coordination",
  "Lighting Design",
  "Ritual Coordination",
  "Bridal Styling",
  "Tailoring & Alterations",
];



const jobTypes = [
  "Full-time",
  "Part-time",
  "Freelance",
  "Contract-based",
  "Per Event",
  "Weekend-only",
  "Onsite",
  "Hybrid",
];

const experienceLevels = [
  "Entry Level",
  "Intermediate",
  "Experienced",
  "Senior",
  "Expert",
];

const projectDurations = [
  "One-day Event",
  "2-3 Days",
  "1 Week",
  "2-4 Weeks",
  "1-3 Months",
  "Ongoing",
];

const budgetOptions = [
  "Fixed Price",
  "Hourly Rate",
  "Package-based",
  "Negotiable",
];

const additionalTags = [
  "Urgent",
  "Flexible Deadline",
  "Budget Friendly",
  "Premium",
  "Destination Wedding",
  "Traditional Ceremony",
  "Modern Theme",
  "Indoor Venue",
  "Outdoor Venue",
  "Last-minute Booking",
  "Kathmandu Valley",
  "Multi-day Event",
];

module.exports = {
  users,
  countries,
  ongoingProjects,
  jobCategories,
  skills,
  jobTypes,
  experienceLevels,
  projectDurations,
  budgetOptions,
  additionalTags,
  languageTags,
};
